### ISSUE TITLE
java.lang.IllegalStateException: Module entity with name when syncing gradle

### ISSUE THREAD

**Issue by teddy-choe** [GisoBartels/kaster#94]
A build error occurs when first sync gradle.
The reason is that **rootproject.name in the settings.gradle file is written in uppercase letters**.
it may occur depending on the Android Studio version or machine.

Android Studio Version: Android Studio Hedgehog | 2023.1.1 Canary 16
Machine: MacBook Pro(intel based)

**Comment by GisoBartels** [comment]
Closed by #100
